# Generated by Django 5.0.6 on 2024-06-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='get_coin_model',
            new_name='currency_model',
        ),
    ]
