# Generated by Django 5.0.6 on 2024-06-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_get_coin_model_currency_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency_model',
            old_name='coin_names',
            new_name='names',
        ),
    ]
